export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'
export const NEW = 'NEW'
export const PLAYING = 'PLAYING'
export const END = 'END'
export const TOGGLE_RATE = 'TOGGLE_RATE'

export const RECEIVE_CHANNELS = 'RECEIVE_CHANNELS'
export const TOGGLE_CHANNELS_SHOW = 'TOGGLE_CHANNELS_SHOW'
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL'

export const SHOW_LOGIN = 'SHOW_LOGIN'
export const HIDE_LOGIN = 'HIDE_LOGIN'
export const LOGINING = 'LOGINING'
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
